logging:
  level:
    com:
      example: TRACE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=swdex
    username: swdex
    password: password
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
